export const audienceSnapshot = Object.freeze({
  totalFollowers: 118000,
  averageViews: 127,
  identifiedFans: 5842,
  directConnections: 1926,
  connectedPlatforms: 4,
});

export const demoFans = [
  {
    id: "fan_01JQ2K1",
    displayName: "Amara K.",
    location: "Lagos, NG",
    channels: ["instagram", "spotify", "email"],
    consentedChannels: ["email"],
    lastSeen: "2h ago",
    metrics: {
      engagements30d: 19,
      daysSinceEngagement: 0,
      activeWeeks8: 8,
      spend180d: 220,
      linkedPlatforms: 3,
      directOptIn: true,
      referrals180d: 4,
    },
  },
  {
    id: "fan_01JQ2K2",
    displayName: "Tobi A.",
    location: "London, UK",
    channels: ["tiktok", "youtube", "sms"],
    consentedChannels: ["sms"],
    lastSeen: "1d ago",
    metrics: {
      engagements30d: 14,
      daysSinceEngagement: 1,
      activeWeeks8: 7,
      spend180d: 60,
      linkedPlatforms: 3,
      directOptIn: true,
      referrals180d: 1,
    },
  },
  {
    id: "fan_01JQ2K3",
    displayName: "Nia R.",
    location: "Atlanta, US",
    channels: ["youtube", "spotify"],
    consentedChannels: [],
    lastSeen: "4d ago",
    metrics: {
      engagements30d: 10,
      daysSinceEngagement: 4,
      activeWeeks8: 6,
      spend180d: 0,
      linkedPlatforms: 2,
      directOptIn: false,
      referrals180d: 2,
    },
  },
  {
    id: "fan_01JQ2K4",
    displayName: "Musa D.",
    location: "Abuja, NG",
    channels: ["instagram", "email"],
    consentedChannels: ["email"],
    lastSeen: "9d ago",
    metrics: {
      engagements30d: 6,
      daysSinceEngagement: 9,
      activeWeeks8: 4,
      spend180d: 45,
      linkedPlatforms: 2,
      directOptIn: true,
      referrals180d: 0,
    },
  },
  {
    id: "fan_01JQ2K5",
    displayName: "Chloe S.",
    location: "Paris, FR",
    channels: ["tiktok"],
    consentedChannels: [],
    lastSeen: "31d ago",
    metrics: {
      engagements30d: 2,
      daysSinceEngagement: 31,
      activeWeeks8: 2,
      spend180d: 0,
      linkedPlatforms: 1,
      directOptIn: false,
      referrals180d: 0,
    },
  },
];
